### ISSUE TITLE
Broken in current vscode

### ISSUE THREAD

**Issue by ArcadeTV** [tomoki1207/vscode-input-sequence#14]
I love the extension, but it broke in some latest version of vscode.
In a blank file with 10 lines, when I call Alt+Ctrl+0 and enter `1+1` I get this output:

```
111
222
333
444
555
666
777
888
999
101010
```

I would appreciate if you could find the time to look into the issue.
Thank you very much!

**Comment by szkaym** [comment]
Hi,

I found it solution for this error.

set "Replace Selection"  in settings.

<img width="236" alt="スクリーンショット 2023-02-16 16 47 26" src="https://user-images.githubusercontent.com/1326428/219300763-fe9cc9d9-8ac5-4ddd-b183-ccc71d2474fc.png">

**Comment by ArcadeTV** [comment]
That works!
Thank you very much!!

**Comment by manjuu-eater** [comment]
Thank you for the nice solution!
I am now able to use this extension.

But, the extension is still broken...
"Replace Selection" is option to replace / not replace selected text.

Could you please reopen this Issue?

Thank you in advance.

**Comment by hsandt** [comment]
Same issue, but I see the project has been unmaintained for 7 years, so I'll switch to VS Sequential Number although it has fewer features.

If you really need extra features like digit number, I suppose checking Replace Selection as a hack to avoid redundant number preview is worth it. Note that the bug is only in preview: after pressing Enter, the numbers are only added once.
